/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_BasicSafetyMessage_H_
#define	_BasicSafetyMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRCmsgID.h"
#include "BSMblob.h"
#include "TestDataFrameV2VI.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VehicleSafetyExtension;
struct VehicleStatus;
struct VehicleDataV2VI;

/* BasicSafetyMessage */
typedef struct BasicSafetyMessage {
	DSRCmsgID_t	 msgID;
	BSMblob_t	 blob1;
	struct VehicleSafetyExtension	*safetyExt	/* OPTIONAL */;
	struct VehicleStatus	*status	/* OPTIONAL */;
	struct VehicleDataV2VI	*vehicleDataV2VI	/* OPTIONAL */;
	TestDataFrameV2VI_t	*testDataFrameV2VI	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BasicSafetyMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BasicSafetyMessage;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VehicleSafetyExtension.h"
#include "VehicleStatus.h"
#include "VehicleDataV2VI.h"

#endif	/* _BasicSafetyMessage_H_ */
#include <asn_internal.h>
