/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#ifndef	_TestDataFrameV2VI_H_
#define	_TestDataFrameV2VI_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TestDataFrameV2VI */
typedef OCTET_STRING_t	 TestDataFrameV2VI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TestDataFrameV2VI;
asn_struct_free_f TestDataFrameV2VI_free;
asn_struct_print_f TestDataFrameV2VI_print;
asn_constr_check_f TestDataFrameV2VI_constraint;
ber_type_decoder_f TestDataFrameV2VI_decode_ber;
der_type_encoder_f TestDataFrameV2VI_encode_der;
xer_type_decoder_f TestDataFrameV2VI_decode_xer;
xer_type_encoder_f TestDataFrameV2VI_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _TestDataFrameV2VI_H_ */
#include <asn_internal.h>
