/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_R36_Source.ASN"
 * 	`asn1c -S ../../../../tools/asn1c/skeletons -pdu=BasicSafetyMessage -fcompound-names`
 */

#include "VehicleDataV2VI.h"

static asn_TYPE_member_t asn_MBR_VehicleDataV2VI_1[] = {
	{ ATF_POINTER, 5, offsetof(struct VehicleDataV2VI, height),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleHeight,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"height"
		},
	{ ATF_POINTER, 4, offsetof(struct VehicleDataV2VI, bumpers),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BumperHeights,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bumpers"
		},
	{ ATF_POINTER, 3, offsetof(struct VehicleDataV2VI, mass),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleMass,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mass"
		},
	{ ATF_POINTER, 2, offsetof(struct VehicleDataV2VI, trailerWeight),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TrailerWeight,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"trailerWeight"
		},
	{ ATF_POINTER, 1, offsetof(struct VehicleDataV2VI, type),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"type"
		},
};
static ber_tlv_tag_t asn_DEF_VehicleDataV2VI_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_VehicleDataV2VI_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* height at 97 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* bumpers at 98 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* mass at 99 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* trailerWeight at 100 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* type at 101 */
};
static asn_SEQUENCE_specifics_t asn_SPC_VehicleDataV2VI_specs_1 = {
	sizeof(struct VehicleDataV2VI),
	offsetof(struct VehicleDataV2VI, _asn_ctx),
	asn_MAP_VehicleDataV2VI_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_VehicleDataV2VI = {
	"VehicleDataV2VI",
	"VehicleDataV2VI",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_VehicleDataV2VI_tags_1,
	sizeof(asn_DEF_VehicleDataV2VI_tags_1)
		/sizeof(asn_DEF_VehicleDataV2VI_tags_1[0]), /* 1 */
	asn_DEF_VehicleDataV2VI_tags_1,	/* Same as above */
	sizeof(asn_DEF_VehicleDataV2VI_tags_1)
		/sizeof(asn_DEF_VehicleDataV2VI_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_VehicleDataV2VI_1,
	5,	/* Elements count */
	&asn_SPC_VehicleDataV2VI_specs_1	/* Additional specs */
};

